### ISSUE TITLE
Does this support zeromq?

### ISSUE THREAD

**Issue by encryptblockr** [kylemanna/docker-bitcoind#106]
Trying to setup websocket connection to bitcoin node
based on the zeromq documentation here https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md

does this docker image support zeromq setup?

**Comment by dev7ba** [comment]
I'm using it without problems in mempoolexplorer.com. but I haven't pushed the code yet.

**Comment by encryptblockr** [comment]
can you please share what you did? here is my `bitcoin.conf` file

```
testnet=0
regtest=0
server=1
rpcuser=test-user
rpcpassword=test-password
rpcport=8332
maxconnections=32
printtoconsole=1
prune=1024
zmqpubrawblock=tcp://127.0.0.1:3000
zmqpubrawtx=tcp://127.0.0.1:3000
zmqpubhashtx=tcp://127.0.0.1:3000
zmqpubhashblock=tcp://127.0.0.1:3000
```

here is `docker-compose.yaml`

```
version: '3.9'

services:
  bitcoin:
    image: kylemanna/bitcoind
    restart: always
    container_name: bitcoin
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - bitcoin-data:/bitcoin/.bitcoin
    ports:
      - 8333:8333   #p2p network
      - 8332:8332   #rpc
      - 3000:3000   #zeromq

volumes:
  bitcoin-data:
    name: bitcoin-data
```

and here is how i ran the container

```
docker compose -p bitcoin -f docker-compose.yaml up -d --build
```


but it is not working when i try to connect to it via port 3000

**can you please tell me what i need to do or change for it to work? will really appreciate it**
thanks
