### ISSUE TITLE
Cannot access rpc after upgrading

### ISSUE THREAD

**Issue by dolgopolovwork** [kylemanna/docker-bitcoind#61]
I cannot access rpc services after upgrade anymore. This is how I configured bitcoind:
```
  d3-btc-node0:
    image: kylemanna/bitcoind:latest
    container_name: d3-btc-node0
    ports:
      - 8332:8332
      - 8333:8333
      - 18333:18333
      - 18444:18444
    entrypoint:
      - bitcoind
      - --rpcuser=test
      - --rpcpassword=test
      - --regtest=1
      - --server=1
      - --rpcallowip=::/0
      - --rpcport=8332
```
Whenever I call `bitcoin-cli --regtest generate 1` it answers with 
```
error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
```
Before upgrade everything was ok. What is wrong?
